### PR TITLE
Add joda convert dependency

### PR DESCRIPTION
**Pull request by joshvfleming**
This is needed for some joda time functions

### CODE REVIEW

**Comment by joshvfleming** [comment]
@XianXing Please review. This is a follow-on to #79 -- it's currently blocking our internal build.

**Comment by ashelkovnykov** [comment]
LGTM pending Travis success

**Comment by XianXing** [comment]
LGTM.

I noticed the PCL failure for our li-photon-ml wrapper, do you know why such failure can't be captured by Travis build?

**Comment by joshvfleming** [comment]
No idea @XianXing. It worked on every machine I threw at it besides our internal Hudson. I guess it's safer to include this here and cover for all environments, though.

**Pull request merged**
