### PR TITLE
Deprecate 'save-models-to-hdfs'. Add new parameter to control model output.

### PR DESCRIPTION
**Pull request by ashelkovnykov**
Addresses issue #84.

Tested on the LinkedIn internal grid. With 'save-models-to-hdfs' set to false, only the best model was output.

### CODE REVIEW

**Comment by XianXing** [comment]
Hmm, I like the idea to separate the logic of saving *all* models versus saving the *best* model.

But there is one more thing to note: sometimes the main purpose of a modeler to run GAME is to tune different hyper-parameters and try different modeling ideas, in order to determine the best hyper-parameter(s) to use for offline/online scoring and model serving. And in those use cases, the user may or may not want GAME to output any models, even the "best" model, to HDFS. Because sometimes the model can be large and would unnecessarily consume disk space, and the modeler may just want to take a look at the evaluation metric and check her modeling idea and nothing more.

Is there any way that we can separate the saving all models from the saving best model logic, while still  providing the modelers the option of not saving any models?

**Comment by joshvfleming** [comment]
Yeah. This seems like a multi-mode kind of situation. E.g.:

```latex
saveModels \in \{ all, bestOnly, none \}
```

**Comment by ashelkovnykov** [comment]
Going to do another test, will post results here when available.

**Comment by ashelkovnykov** [comment]
Added some integration tests and tested on the LinkedIn internal grid, works fine.

**Comment by XianXing** [comment]
LGTM

**Pull request merged**
