### PR TITLE
Decrease the integTest running time for driver by avoiding running ex…

### PR DESCRIPTION
**Pull request by XianXing**
…cessive number of iterations.

IntegTest duration for Photon's Driver on my laptop (running time numbers are from tests reports)
before: 26m27.52s
after: 10m46.76s

Overall integTest running time on Travis:
before: 34 min 4 sec
after: 26 min 30 sec

Not by a lot... But still a little bit faster than before.

This PR addresses issue #19.

### CODE REVIEW

**Comment by joshvfleming** [comment]
@XianXing I have a commit that fixes the failure. Can you give me access to your fork?

**Comment by XianXing** [comment]
Thanks Josh!

**Comment by ashelkovnykov** [comment]
Why did @XianXing's changes cause failures relating to infinity/NaN?

**Comment by joshvfleming** [comment]
@ashelkovnykov Reducing the number of training iterations caused the fitting diagnostic code to produce  NaN / Infinity values for some of the Poisson models.

**Comment by ashelkovnykov** [comment]
Thanks @joshvfleming. LGTM

**Pull request merged**
